language: node_js
sudo: false
node_js:
node_js:
- "stable"
before_script:
- npm install -g gitbook-cli
- gitbook fetch $GITBOOK_VERSION
env:
 matrix:
   - GITBOOK_VERSION=3.1
   - GITBOOK_VERSION=3.2
   - GITBOOK_VERSION=latest
deploy:
  provider: npm
  email: todvora@gmail.com
  api_key:
    secure: W2yYn+A6i/t0lJY9ikIHisv3sUE1AWei1HcXMssJYFox/qLBvyXHl4SXdM0lPGaQOS/y9kt13Lo2SMv2J8KS4MPxEiLcYEyFNz0XdpR9swbeg2t6RirsCZcqCoSGx66sI1w3jv9N2tWCnrZBpL62m2yoKldmpgXHIwnwLEMySvU=
  on:
    tags: true
    condition: "$GITBOOK_VERSION = latest"
    repo: todvora/gitbook-plugin-image-captions
